# Generated by Django 5.1.6 on 2025-03-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='img',
            field=models.URLField(default='https://st3.depositphotos.com/1267918/12607/v/950/depositphotos_126077094-stock-illustration-restaurant-menu-card-design.jpg'),
        ),
    ]
